top_users = {
    "airbnb_hosts" : ['toy200275', 'KnowBuddyReally42', 'madaon', 'putting1nwork', 'jacshit', 'accidental_hippy', 'ragamuffinshop'],
    "AirBnB" : ['personabledressgummy', 'beautifulplanet', 'Enough_Insurance', 'koavf', 'ricosalsa'],
    "AmazonFlexDrivers" : ['TigerKneeCrush', 'Tricktrick_', 'Pierre509', 'Amc724', 'DriverDriver6699', 'CapnShinerAZ', 'ultimatefighting'],
    "CaregiverSupport" : ['AutoModerator', 'dumb_giraffe', 'cheap_dates', 'elderscare', 'sharkytimes1326', 'caribbeanturtle'],
    "couchsurfing" : ['drak0bsidian', 'subaculture', 'Fmtpires', 'maliciousass'],
    "doordash_drivers" : ['NoobSlayerDill', 'stevester90', 'feetkisser69', 'nyQu1lKl0wn', 'iv2892', 'grggsctt', 'skylercollins', 'DaGR2310'],
    "doordash" : ['antoniolens92', 'jcwainc', 'TheGame81677', 'mirandanielcz'],
    "Etsy" : ['coocoodove', 'typoeverafter', 'hudsonstudio', 'supercat369', 'BearsAndCupcakes'],
    "EtsySellers" : ['whoinvitedthesepeopl', 'charfiee', 'Kikithekoala', 'mallory-onthe-moon', 'danibanani19', 'DeeInWV', 'WhatTheFlippityFlop', 'EtsyTruther'],
    "Fiverr" : ['emmakifiverr', 'elonsmusketer', 'abdullahmnsr2', 'Tiniest_ATINY', 'sadooooo2019'],
    "grubhubdrivers" : ['TheGame81677', 'johnnewburg', 'Mamba-Dasher24', 'chillip135', '1cuntasaurus'],
    "instacart" : ['marsirack', 'Pawket23', 'LienHoang9391', 'Allansknowledge7', 'TopShelfService', 'Shaneisyourdad', 'cajunflavoredbob', 'candycarmel96689'],
    "InstacartShoppers" : ['tr1ni', 'djsekani', 'alattesmiles', 'funkyjared', 'd_HOME', 'DavePi81', '954courier', 's_slayer'],
    "Lyft" : ['ActualFunny', 'xerxes7777', 'SFUber', 'skywaybum', 'SlicerLeo', 'sfxnyc'],
    "lyftdrivers" : ['mythrowawaysilly', 'VegasGuy1223', 'cwgzz81', 'baramobacka', 'skywaybum', 'ActualFunny', 'fitfulbrain', 'Rojo0416'],
    "mturk" : ['AutoModerator', 'Franklin551'],
    "MusicEd" : ['Josquin_TheMan', 'lukamu', 'MaryKMcDonald', 'solvent-throwaway', 'YankeeinDixie'],
    "Nanny" : ['AutoModerator', 'nannybabywhisperer', 'Thedailybee', 'Waterproof_soap', 'cynflowers'],
    "postmates" : ['FlyingChalupa', 'Jz9786', 'AutoModerator', 'LV-Knight', 'thetallestwizard', 'kuro41'],
    "RoverPetSitting" : ['tequila_mockingbirds', 'dancer315', 'drinkiethebear', 'poopqueenurchin'],
    "ShiptShoppers" : ['stardorsdash', 'alattesmiles', 'nikki_11580', 'JkLion1998', 'cfrazierjr', 'booanxietysucks', 't3chb1zn3ss', 'cajunflavoredbob', 'jo_ezzy', 'yourfriendlyghost98'],
    "TaskRabbit" : ['panzerXdivision', 'shortfriday', 'HooRYoo', 'belly_of_eggs', 'thenewmook', 'mdoney10'],
    "TurkerNation" : ['TNModerator', 'duckduckpass', 'lpturktest', 'asawy006'],
    "uber" : ['vigorous', 'ActualFunny', 'xerxes7777', 'skywaybum'],
    "uberdrivers" : ['SFUber'],
    "UberEATS" : ['daveishere7', 'Kevlarr1984', 'antoniolens92', 'Mamba-Dasher24', 'MichaelRahmani', 'AutoModerator'],
    "Upwork" : ['oh_noes_wat11', 'ClassicPurist', 'Luke_James', 'Badiha', 'iAccidentally11', 'GigMistress'],
    "vipkid" : ['tedandlisa123', 'Dinofornever', 'nwtay', 'Stealinpicnicbaskets', 'hannahmel', 'richljames', 'sweetthang1972'],
    "vrbo" : ['Stinkynelson', 'StinklePink', 'DJCashEel', 'I_Am_Not_Okay', 'NazChat']
}